services:
  messagebroker:
    image: rabbitmq:management-alpine

  contacts.db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  contact-persistence:
    image: ${DOCKER_REGISTRY-}contact-persistence
    build:
      context: ./Services/ContactPersistence
      dockerfile: ContactPersistence/Dockerfile

  create-contact.api:
    image: ${DOCKER_REGISTRY-}create-contact.api
    build:
      context: ./Services/CreateContact-API
      dockerfile: src/CreateContact.API/Dockerfile

  contactmanager.apigateway:
    image: ${DOCKER_REGISTRY-}contactmanager.apigateway
    build:
      context: .
      dockerfile: ContactManager.ApiGateway/Dockerfile
