global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["contactmanager.apigateway:8080"]

  - job_name: "create-contact-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["create-contact.api:8080"]
  
  - job_name: "update-contact-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["update-contact.api:8080"]

  - job_name: "delete-contact-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["delete-contact.api:8080"]

  - job_name: "rabbitmq"
    static_configs:
      - targets:
        - "messagebroker:15692"