name: CI/CD Pipeline - API Gateway

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./ContactManager.sln
      
    - name: Build
      run: dotnet build ./ContactManager.sln --no-restore
      
    - name: Test
      run: dotnet test ./ContactManager.sln --no-build --verbosity normal

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/contact-api-gateway:latest -f ./ContactManager.ApiGateway/Dockerfile .
    
    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/contact-api-gateway:latest

    - name: Setup Kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.AKS_KUBE_CONFIG }}
        version: 1.21.0

    - name: Deploy to AKS
      run: |
        kubectl apply -f ./k8s
